<?php

namespace AppBundle\Repository\BLog;

/**
 * Producte2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Producte2Repository extends \Doctrine\ORM\EntityRepository
{
}
