USE `netsergi_db_empl`;

# FEM LA VISTA PROJECTES PER EMPLEAT
CREATE VIEW V_PROJECTS_EMPLOYEES
	( PRJT_CODE, PRJT_NAME, EMPL_NUMBER, EMPL_FORNAME, EMPL_SURNAME )
AS 
	SELECT P.PRJT_CODE, P.PRJT_NAME, E.EMPL_NUMBER, E.EMPL_FORNAME, E.EMPL_SURNAME
    FROM T_PROJECTS P
    INNER JOIN T_PROJECTS_EMPLOYEES PE
			   ON P.PRJT_ID = PE.PRJT_ID
	INNER JOIN T_EMPLOYEES E
			   ON PE.EMPL_ID = E.EMPL_ID;
               
#--------------------------------------------------------

SELECT * FROM V_PROJECTS_EMPLOYEES
WHERE PRJT_CODE LIKE 'EXT%'
ORDER BY EMPL_FORNAME DESC;

