use `netsergi_db_empl`;

#-----------------------------------------------------------------

SELECT EMP.EMPL_FORNAME, EMP.EMPL_SURNAME, OFC.OFFC_CITY, KNW.KNLN_NAME, EMP.EMPL_MENTOR_ID
FROM T_EMPLOYEES EMP
INNER JOIN t_offices OFC
		   ON EMP.OFFC_ID = OFC.OFFC_ID
LEFT OUTER JOIN T_KNOWLEDGE_LINES KNW
		   ON EMP.KNLN_ID = KNW.KNLN_ID
WHERE 
OFC.OFFC_COUNTRY IN ('España','Chile') 
AND EMP.EMPL_MENTOR_ID IS NULL;

#-----------------------------------------------------------------

SELECT P.PRJT_CODE 'CODI', P.PRJT_NAME 'NOM PROJECTE', 
E.EMPL_NUMBER 'NUMERO EMPLEAT', E.EMPL_SURNAME 'COGNOM EMPLEAT'
FROM T_PROJECTS P
INNER JOIN T_PROJECTS_EMPLOYEES PE
		   ON PE.PRJT_ID = P.PRJT_ID
INNER JOIN T_EMPLOYEES E
		   ON E.EMPL_ID = PE.EMPL_ID
WHERE E.EMPL_FORNAME = 'Juan';