USE `netsergi_db_empl`;


# ES CREA FOREIGN KEY A LA TAULA EMPLOYEES PER RELACIONAR-LA AMB OFICINA I LINEA DE CONEIXEMENT ----
ALTER TABLE T_EMPLOYEES 
    ADD INDEX FK_EMPL_OFFC (OFFC_ID), 
    ADD CONSTRAINT FK_EMPL_OFFC 
        FOREIGN KEY (OFFC_ID) 
        REFERENCES t_offices (OFFC_ID);

ALTER TABLE T_EMPLOYEES 
    ADD INDEX FK_EMPL_KNLN (KNLN_ID), 
    ADD CONSTRAINT FK_EMPL_KNLN 
        FOREIGN KEY (KNLN_ID) 
        REFERENCES T_KNOWLEDGE_LINES (KNLN_ID);

# PROBES PER COMPROBAR INTEGRITAT REFERENCIAL
UPDATE T_EMPLOYEES 
SET OFFC_ID = 40 
WHERE EMPL_ID = 1;

DELETE FROM t_offices 
WHERE OFFC_ID = 10;

# FEM CLAUS FORANEAS DE LA TAULA PROJECT_EMPLOYESS A EMPLOYEES I PROJECTS
ALTER TABLE `T_PROJECTS_EMPLOYEES`
	ADD INDEX FK_PREM_PRJT (PRJT_ID),
    ADD CONSTRAINT FK_PREM_PRJT
		FOREIGN KEY (PRJT_ID)
        REFERENCES T_PROJECTS(PRJT_ID);
        
ALTER TABLE `T_PROJECTS_EMPLOYEES`
	ADD INDEX FK_PREM_EMPL (EMPL_ID),
    ADD CONSTRAINT FK_PREM_EMPL
		FOREIGN KEY (EMPL_ID)
        REFERENCES T_EMPLOYEES(EMPL_ID);
        
DELETE FROM T_PROJECTS WHERE PRJT_ID = 2;     