USE `netsergi_db_empl`;

# CREAR TAULA PROJECTES -------------------------------
CREATE TABLE `T_PROJECTS` (
  `PRJT_ID` INT NOT NULL  AUTO_INCREMENT,
  `PRJT_CODE` VARCHAR(16) NOT NULL,
  `PRJT_NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PRJT_ID`));
 
# CREAR TAULA INTERMITJA PROJECTE - EMPLEATS ----------
  CREATE TABLE `T_PROJECTS_EMPLOYEES` (
  `PRJT_ID` INT NOT NULL,
  `EMPL_ID` INT NOT NULL,
  PRIMARY KEY (`PRJT_ID`,`EMPL_ID`));

# INSERIM DOS PROJECTES
INSERT INTO T_PROJECTS 
(
	`PRJT_CODE`, 
    `PRJT_NAME`
)
VALUES
(
	'EXT-001000-01234',
    'Gestión de usuarios'
),
(
	'INT-001000-03200',
	'Cursos de formación'
);

# ASSOCIEM PRODUCTES A EMPLEATS -------------
INSERT INTO `T_PROJECTS_EMPLOYEES`
VALUES
(
	1,
    1   
),
(
	2,
	1
),
(
	1,
    2
);