USE `netsergi_tenda_informatica`;

# --------------------------------------------------------------------

CREATE TABLE T_FABRICANT
(
	FAB_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FAB_NOM VARCHAR(100),
    FAB_NACIONALITAT VARCHAR(50)
);
  
CREATE TABLE T_ARTICLES 
(
	ARTIC_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ARTIC_NOM VARCHAR(50),
    ARTIC_PREU DOUBLE,
    FAB_ID INT NOT NULL,
	INDEX FK_FAB_ID (FAB_ID),
    CONSTRAINT FK_FAB_ID 
    FOREIGN KEY (FAB_ID)
    REFERENCES T_FABRICANT (FAB_ID)
);

ALTER TABLE T_ARTICLES MODIFY ARTIC_PREU DECIMAL(5,2);

# --------------------------------------------------------------------

INSERT INTO T_FABRICANT 
(
	FAB_NOM,
    FAB_NACIONALITAT
)
VALUES
(
	'ASUS',
    'China'
),
(
	'LOGITECH',
    'Suiza'
),
(
	'NVIDIA',
    'USA'
),
(
	'ATI',
    'Canadá'
),
(
	'KINGSTON',
    'USA'
),
(
	'SEAGATE',
    'USA'
),
(
	'ACER',
    'Taiwan'
);


#------------------------------------------------------------

SELECT ARTIC_NOM ARTICLES, CONCAT(ARTIC_PREU,' €') PREU FROM T_ARTICLES;


SELECT A.ARTIC_NOM ARTICLES, A.ARTIC_PREU PREU, F.FAB_NOM FABRICANT
FROM T_ARTICLES A
INNER JOIN T_FABRICANT F
		   ON A.FAB_ID = F.FAB_ID
WHERE F.FAB_NOM = 'NVIDIA'
AND ARTIC_PREU BETWEEN 160 AND 300;

SELECT ARTIC_NOM ARTICLE, REPLACE(FORMAT(ROUND((ARTIC_PREU * 166.386)),0),',','.') PESETAS FROM T_ARTICLES;
           
SELECT CONCAT(FORMAT(AVG(A.ARTIC_PREU),2),' €') 'MITJANA PREU PRODUCTES KINGSTON'
FROM T_ARTICLES A
INNER JOIN T_FABRICANT F
		   ON F.FAB_ID = A.FAB_ID
WHERE F.FAB_NOM = 'KINGSTON';

SELECT COUNT(*) 'NUMERO D''ARTICLES > 180€'
FROM T_ARTICLES
WHERE ARTIC_PREU > 180;

SELECT F.FAB_NOM NOM_FABRICANT, REPLACE(CONCAT(FORMAT(AVG(A.ARTIC_PREU),2),' €'),'.',',') PREU_MITJA
FROM T_ARTICLES A
INNER JOIN T_FABRICANT F
		   ON F.FAB_ID = A.FAB_ID
GROUP BY F.FAB_NOM;

